# Generated by Django 4.1.6 on 2023-02-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(blank=True, max_length=30, null=True, verbose_name='国')),
                ('market', models.CharField(blank=True, max_length=20, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('division', models.CharField(blank=True, max_length=20, null=True)),
                ('industry_code_1', models.CharField(blank=True, max_length=10, null=True)),
                ('industry_division_1', models.CharField(blank=True, max_length=10, null=True)),
                ('industry_code_2', models.CharField(blank=True, max_length=10, null=True)),
                ('industry_division_2', models.CharField(blank=True, max_length=10, null=True)),
                ('scale_code', models.CharField(blank=True, max_length=10, null=True)),
                ('scale_division', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_code', models.CharField(blank=True, max_length=30, null=True)),
                ('trade_date', models.DateField(blank=True, null=True)),
                ('open_value', models.FloatField(blank=True, null=True, verbose_name='始値')),
                ('close_value', models.FloatField(blank=True, null=True, verbose_name='終値')),
                ('high_value', models.FloatField(blank=True, null=True, verbose_name='高値')),
                ('low_value', models.FloatField(blank=True, null=True, verbose_name='安値')),
                ('volume', models.IntegerField(blank=True, null=True, verbose_name='出来高')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand')),
            ],
        ),
    ]
