# Generated by Django 4.1.6 on 2023-02-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='industry_code_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
