# Generated by Django 4.1.6 on 2023-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_brand_industry_code_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='industry_code_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='industry_division_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
