# Generated by Django 4.1.6 on 2023-03-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_brand_industry_code_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trades',
            old_name='close_value',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='trade_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='high_value',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='low_value',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='trades',
            old_name='open_value',
            new_name='Open',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='volume',
        ),
        migrations.AddField(
            model_name='trades',
            name='Volume',
            field=models.FloatField(blank=True, null=True, verbose_name='出来高'),
        ),
    ]
